const $ = (selector, parent = document) => parent.querySelector(selector);
const $$ = (selector, parent = document) => [...parent.querySelectorAll(selector)];

const menu = $('.menu-toggle');
const nav = $('.main-nav');
menu.addEventListener('click', () => { const open = nav.classList.toggle('open'); menu.setAttribute('aria-expanded', open); menu.textContent = open ? '×' : '☰'; });
$$('.main-nav a').forEach(a => a.addEventListener('click', () => { nav.classList.remove('open'); menu.textContent = '☰'; menu.setAttribute('aria-expanded', 'false'); }));

const dialog = $('#curriculum-dialog');
const mallas = {
  'image3.png': ['assets/mallas-2026/image3.png', 'Malla curricular adjunta: Ciberseguridad.'],
  'image4.png': ['assets/mallas-2026/image4.png', 'Malla curricular adjunta: Diseño de Productos Industriales Textiles.'],
  'image5.png': ['assets/mallas-2026/image5.png', 'Malla curricular adjunta: Contabilidad.'],
  'image6.png': ['assets/mallas-2026/image6.png', 'Malla curricular adjunta: Ejecutivo Comercial y Servicio al Cliente.'],
  'image7.png': ['assets/mallas-2026/image7.png', 'Malla curricular de referencia: Electromecánica.'],
  'textiles-2027.png': ['assets/malla-textiles-2027.png', 'Estructura curricular adjunta: Diseño de Productos Industriales Textiles.']
};
$$('.curriculum-trigger').forEach(button => button.addEventListener('click', () => { if (!button.dataset.curriculum) return; const [src, caption] = mallas[button.dataset.curriculum]; $('#curriculum-image').src = src; $('#curriculum-caption').textContent = caption; dialog.showModal(); }));
$('.dialog-close').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', e => { if (e.target === dialog) dialog.close(); });

const choices = { electro: 'Opción proyectada: mantenimiento industrial, refrigeración, control y sistemas de aire acondicionado.', moda: 'Opción proyectada: creación, confección, diseño y emprendimiento textil.' };
$$('.choice').forEach(btn => btn.addEventListener('click', () => { $$('.choice').forEach(x => x.classList.remove('active')); btn.classList.add('active'); $('#choice-text').textContent = choices[btn.dataset.option]; }));

$$('[data-date]').forEach(item => { const passed = new Date(`${item.dataset.date}T23:59:00`) < new Date(); if (passed) { item.classList.add('completed'); item.setAttribute('aria-label', 'Fecha cumplida'); item.querySelector('i').textContent = '✓'; } });

const samplePosts = [
  { id: 'welcome', name: 'Equipo STN', initials: 'ST', time: 'Información oficial', text: '¡Bienvenidas y bienvenidos! Usá este espacio para consultar sobre el proceso de admisión 2027.', likes: 14 },
  { id: 'guide', name: 'Orientación STN', initials: 'OR', time: 'Hace poco', text: 'Recordá completar la pre-matrícula y reservar tu cita para entrevista o examen.', likes: 8 }
];
function loadPosts() { return JSON.parse(localStorage.getItem('stn-posts') || 'null') || samplePosts; }
function savePosts(posts) { localStorage.setItem('stn-posts', JSON.stringify(posts)); }
function renderPosts() {
  const posts = loadPosts();
  $('#feed').innerHTML = posts.map(post => `<article class="post"><div class="post-meta"><span class="avatar">${post.initials}</span><div><b>${post.name}</b><small>${post.time}</small></div></div><p class="post-body">${escapeHtml(post.text)}</p><div class="post-actions"><button class="like-button ${post.liked ? 'liked' : ''}" data-id="${post.id}">♡ ${post.likes || 0} Me interesa</button><button type="button">◌ Consultar</button></div></article>`).join('');
  $$('.like-button').forEach(button => button.addEventListener('click', () => { const items = loadPosts(); const post = items.find(x => x.id === button.dataset.id); post.liked = !post.liked; post.likes = Math.max(0, (post.likes || 0) + (post.liked ? 1 : -1)); savePosts(items); renderPosts(); }));
}
function escapeHtml(text) { const el = document.createElement('div'); el.textContent = text; return el.innerHTML; }
const postText = $('#post-text');
postText.addEventListener('input', () => $('.character-count').textContent = `${postText.value.length} / 400`);
$('#post-form').addEventListener('submit', e => { e.preventDefault(); const text = postText.value.trim(); if (!text) return; const posts = loadPosts(); posts.unshift({ id: Date.now().toString(), name: 'Consulta de visitante', initials: 'CV', time: 'Ahora', text, likes: 0 }); savePosts(posts); postText.value = ''; $('.character-count').textContent = '0 / 400'; renderPosts(); });
renderPosts();

function getStudents() { return JSON.parse(localStorage.getItem('stn-students') || '[]'); }
function getDocs() { return JSON.parse(localStorage.getItem('stn-documents') || '[]'); }
function getAppointments() { return JSON.parse(localStorage.getItem('stn-appointments') || '[]'); }
function renderAppointments(filter = 'Todas') { const list = getAppointments().filter(a => filter === 'Todas' || a.specialty === filter); $('#appointments-list').innerHTML = list.length ? list.map(a => `<div class="appointment-row"><div><b>${escapeHtml(a.name)}</b><small>${escapeHtml(a.specialty)} · ${escapeHtml(a.type)} · Prof. ${escapeHtml(a.professor || 'Por asignar')}</small></div><strong>${escapeHtml(a.date)} · ${escapeHtml(a.time)}</strong></div>`).join('') : '<p>No hay citas para esta especialidad.</p>'; }
function updateDashboard() {
  const students = getStudents(), docs = getDocs(), appointments = getAppointments();
  $('#pre-count').textContent = students.filter(s => s.status === 'Pre-matriculado').length; $('#mat-count').textContent = students.filter(s => s.status === 'Matriculado').length; $('#doc-count').textContent = docs.length; $('#appointment-count').textContent = appointments.length;
  $('#student-table').innerHTML = students.length ? students.map(s => `<tr><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.status)}</td><td>${escapeHtml(s.specialty || 'Sin asignar')}</td><td>${escapeHtml(s.contact)}</td></tr>`).join('') : '<tr class="empty-row"><td colspan="4">Aún no hay registros cargados.</td></tr>';
  $('#documents-list').innerHTML = docs.length ? docs.map(d => `<div class="document-item"><span>▧ ${escapeHtml(d.name)}</span><small>${d.date}</small></div>`).join('') : '<p>Los documentos cargados aparecerán aquí.</p>';
  renderAppointments($('.specialty-tab.active')?.dataset.specialty || 'Todas');
}
$('#teacher-login').addEventListener('submit', e => { e.preventDefault(); const message = $('#login-message'); if ($('#teacher-password').value === 'RoyAdmSTN') { $('#teacher-login').classList.add('hidden'); $('#teacher-dashboard').classList.remove('hidden'); sessionStorage.setItem('stn-teacher', 'true'); updateDashboard(); } else { message.textContent = 'Contraseña incorrecta.'; message.classList.add('error'); } });
if (sessionStorage.getItem('stn-teacher')) { $('#teacher-login').classList.add('hidden'); $('#teacher-dashboard').classList.remove('hidden'); updateDashboard(); }
$('#logout').addEventListener('click', () => { sessionStorage.removeItem('stn-teacher'); $('#teacher-dashboard').classList.add('hidden'); $('#teacher-login').classList.remove('hidden'); $('#teacher-password').value = ''; });
$('#add-student').addEventListener('click', () => { const name = prompt('Nombre completo del estudiante:'); if (!name?.trim()) return; const contact = prompt('Teléfono o correo de contacto:') || 'Sin dato'; const choice = prompt('Escribí 1 para Pre-matriculado o 2 para Matriculado:', '1'); const specialty = $('#teacher-specialty').value; const students = getStudents(); students.push({ name: name.trim(), contact: contact.trim(), specialty, status: choice === '2' ? 'Matriculado' : 'Pre-matriculado' }); localStorage.setItem('stn-students', JSON.stringify(students)); updateDashboard(); });
$('#doc-upload').addEventListener('change', e => { const docs = getDocs(); [...e.target.files].forEach(file => docs.unshift({ name: file.name, date: new Date().toLocaleDateString('es-CR') })); localStorage.setItem('stn-documents', JSON.stringify(docs)); e.target.value = ''; updateDashboard(); });
$('#save-appointment').addEventListener('click', () => { const specialty = $('#teacher-specialty').value, type = $('#teacher-appointment-type').value, date = $('#teacher-appointment-date').value, time = $('#teacher-appointment-time').value, name = $('#teacher-candidate').value.trim(), email = $('#teacher-candidate-email').value.trim(), professor = $('#teacher-professor').value.trim(), contact = $('#teacher-candidate-contact').value.trim(), message = $('#teacher-appointment-message'); if (!date || !name || !email || !professor) { message.textContent = 'Completá estudiante, correo, profesor y fecha para guardar.'; message.classList.add('error'); return; } const appointment = { specialty, type, date, time, name, email, professor, contact }; const appointments = getAppointments(); appointments.push(appointment); localStorage.setItem('stn-appointments', JSON.stringify(appointments)); const subject = encodeURIComponent(`Confirmación de cita STN · ${date} · ${time}`); const body = encodeURIComponent(`Hola ${name},\n\nConfirmamos tu cita de ${type.toLowerCase()} en la Sección Técnica Nocturna.\n\nFecha: ${date}\nHora: ${time}\nEspecialidad: ${specialty}\nProfesor a cargo: ${professor}\n\nPara consultas: 6195-5775.`); message.classList.remove('error'); message.innerHTML = `✓ Cita guardada. <a class="confirmation-link" href="mailto:${encodeURIComponent(email)}?subject=${subject}&body=${body}">Abrir correo de confirmación para enviar ↗</a>`; $('#teacher-candidate').value = ''; $('#teacher-candidate-email').value = ''; $('#teacher-professor').value = ''; $('#teacher-candidate-contact').value = ''; updateDashboard(); });
$$('.specialty-tab').forEach(tab => tab.addEventListener('click', () => { $$('.specialty-tab').forEach(t => t.classList.remove('active')); tab.classList.add('active'); renderAppointments(tab.dataset.specialty); }));
$('#edit-ticker').addEventListener('click', () => { const message = prompt('Mensaje institucional visible para la comunidad:', localStorage.getItem('stn-ticker') || $('#ticker-message').textContent); if (message?.trim()) { localStorage.setItem('stn-ticker', message.trim()); $('#ticker-message').textContent = message.trim(); } });
$('#ticker-message').textContent = localStorage.getItem('stn-ticker') || $('#ticker-message').textContent;

const assistantReplies = [
  { keys: ['prematr', 'formulario', 'inscrib', 'inscrip'], text: 'La pre-matrícula 2027 se completa en el formulario oficial. Usá el botón “Pre-matrícula 2027” o escribinos por WhatsApp al 6195-5775.' },
  { keys: ['especial', 'oferta', 'carrera', 'ciber', 'contab', 'comercial', 'aire', 'electrom', 'textil', 'diseño'], text: 'La oferta 2027 incluye Ciberseguridad, Contabilidad, Ejecutivo Comercial y Servicio al Cliente, Mantenimiento de Sistemas de Aire Acondicionado Industrial, Electromecánica y Diseño de Productos Industriales Textiles.' },
  { keys: ['hora', 'horario', 'noche', 'cita', 'examen', 'entrevista'], text: 'Las citas de entrevista y examen las administra cada docente desde el Portal para docentes, de lunes a viernes entre 6:00 p. m. y 9:00 p. m.' },
  { keys: ['whatsapp', 'teléfono', 'telefono', 'contacto', 'ubicación', 'ubicacion'], text: 'Podés contactarnos por WhatsApp al 6195-5775. También encontrás el enlace directo en la página.' },
  { keys: ['docente', 'portal', 'teams'], text: 'El Portal para docentes está protegido y contiene una pestaña por especialidad, agenda, registros y documentos informativos.' }
];
function assistantReply(question) { const q = question.toLowerCase(); const found = assistantReplies.find(item => item.keys.some(key => q.includes(key))); return found?.text || 'Puedo orientarte sobre pre-matrícula, especialidades, horarios de examen y entrevista, Portal docente o WhatsApp. ¿Qué necesitás saber?'; }
const assistantLaunch = $('#assistant-launch'), assistantPanel = $('#assistant-panel'), assistantForm = $('#assistant-form'), assistantInput = $('#assistant-input'), assistantMessages = $('#assistant-messages');
assistantLaunch.addEventListener('click', () => { const open = assistantPanel.classList.toggle('hidden'); assistantLaunch.setAttribute('aria-expanded', String(!open)); if (!open) assistantInput.focus(); });
$('#assistant-close').addEventListener('click', () => { assistantPanel.classList.add('hidden'); assistantLaunch.setAttribute('aria-expanded', 'false'); });
assistantForm.addEventListener('submit', e => { e.preventDefault(); const question = assistantInput.value.trim(); if (!question) return; assistantMessages.insertAdjacentHTML('beforeend', `<div class="assistant-bubble user">${escapeHtml(question)}</div><div class="assistant-bubble">${escapeHtml(assistantReply(question))}</div>`); assistantInput.value = ''; assistantMessages.scrollTop = assistantMessages.scrollHeight; });

// Base CSV local para el portal docente. No se publica en GitHub: se procesa solo en el dispositivo del docente.
const teacherAgenda = $('.teacher-agenda');
if (teacherAgenda) {
  const senderWrap = document.createElement('label'); senderWrap.className = 'teacher-sender-email'; senderWrap.innerHTML = 'Correo del docente que envía<input id="teacher-sender-email" type="email" placeholder="docente@correo institucional" required>'; teacherAgenda.querySelector('.agenda-heading').after(senderWrap);
  const sendButton = document.createElement('button'); sendButton.className = 'btn btn-send-confirmation'; sendButton.id = 'send-confirmation'; sendButton.type = 'button'; sendButton.textContent = 'Enviar confirmación'; sendButton.disabled = true; teacherAgenda.querySelector('#save-appointment').after(sendButton);
  let pendingMailto = '';
  const csvState = { records: [], filter: 'Todas' };
  const actions = teacherAgenda.parentElement.querySelector('.dashboard-actions');
  const csvLabel = document.createElement('label'); csvLabel.className = 'upload-label'; csvLabel.innerHTML = '▣ Importar base CSV<input id="csv-upload" type="file" accept=".csv,text/csv" hidden>'; actions.append(csvLabel);
  const db = document.createElement('section'); db.className = 'database-summary'; db.id = 'database-summary'; db.innerHTML = '<div><b id="db-total">0</b><span>Registros CSV</span></div><div><b id="db-visible">0</b><span>En esta especialidad</span></div><div><b id="db-duplicates">0</b><span>Duplicados detectados</span></div><p id="db-source">Importá la base CSV desde este dispositivo para ver prematrícula y matrícula. La información no se publica.</p><div class="database-table-wrap"><table class="database-table"><thead><tr><th>Estudiante</th><th>Identificación</th><th>Especialidad</th><th>Contacto</th><th>Estado</th><th>Acción</th></tr></thead><tbody id="csv-table-body"><tr><td colspan="6">No hay datos cargados.</td></tr></tbody></table></div>'; actions.after(db);
  function csvParse(text) { const rows = [], row = []; let cell = '', quoted = false; for (let i = 0; i < text.length; i++) { const ch = text[i], next = text[i + 1]; if (ch === '"' && quoted && next === '"') { cell += '"'; i++; } else if (ch === '"') quoted = !quoted; else if (ch === ',' && !quoted) { row.push(cell); cell = ''; } else if ((ch === '\n' || ch === '\r') && !quoted) { if (ch === '\r' && next === '\n') i++; row.push(cell); if (row.some(v => v.trim())) rows.push(row.splice(0)); cell = ''; } else cell += ch; } if (cell || row.length) { row.push(cell); rows.push(row); } const headers = (rows.shift() || []).map(h => h.replace(/^\uFEFF/, '').trim()); return rows.map(values => Object.fromEntries(headers.map((h, i) => [h, (values[i] || '').trim()]))); }
  function field(record, matcher) { const key = Object.keys(record).find(k => matcher.test(k)); return key ? record[key] : ''; }
  function normalizeSpecialty(value) { const v = value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); if (v.includes('refriger') || v.includes('aire acondicionado')) return 'Mantenimiento de Sistemas de Aire Acondicionado Industrial'; if (v.includes('ciber')) return 'Ciberseguridad'; if (v.includes('contab')) return 'Contabilidad'; if (v.includes('comercial') || v.includes('servicio al cliente')) return 'Ejecutivo Comercial y Servicio al Cliente'; if (v.includes('textil') || v.includes('diseño de productos')) return 'Diseño de Productos Industriales Textiles'; if (v.includes('electrom')) return 'Electromecánica'; return value || 'Sin especialidad'; }
  function prepareRecords(raw) { const records = raw.map((r, index) => ({ raw: r, index, name: field(r, /nombre completo/i) || 'Sin nombre', id: field(r, /cedula|documento de identidad/i), email: field(r, /correo electr/i), phone: field(r, /telefono principal/i), specialty: normalizeSpecialty(field(r, /especialidad.*matricular/i)), province: field(r, /provincia/i), canton: field(r, /canton/i), timestamp: field(r, /marca temporal/i) })); const groups = {}; records.forEach(r => { const key = (r.id || r.name).toLowerCase().replace(/\s+/g, ' ').trim(); (groups[key] ||= []).push(r); }); records.forEach(r => { const key = (r.id || r.name).toLowerCase().replace(/\s+/g, ' ').trim(), group = groups[key] || []; r.duplicateSpecialties = [...new Set(group.map(x => x.specialty))]; r.duplicate = group.length > 1; }); return records; }
  function renderDatabase() { const rows = csvState.records.filter(r => csvState.filter === 'Todas' || r.specialty === csvState.filter), duplicateCount = csvState.records.filter(r => r.duplicate).length; $('#db-total').textContent = csvState.records.length; $('#db-visible').textContent = rows.length; $('#db-duplicates').textContent = duplicateCount; $('#db-source').textContent = csvState.records.length ? `Base cargada en este dispositivo · filtro: ${csvState.filter}` : 'Importá la base CSV desde este dispositivo para ver prematrícula y matrícula. La información no se publica.'; $('#csv-table-body').innerHTML = rows.length ? rows.map(r => `<tr class="${r.duplicate ? 'is-duplicate' : ''}"><td><b>${escapeHtml(r.name)}</b><details><summary>Ver todos los datos</summary><dl>${Object.entries(r.raw).map(([k, v]) => `<dt>${escapeHtml(k)}</dt><dd>${escapeHtml(v || '—')}</dd>`).join('')}</dl></details></td><td>${escapeHtml(r.id || '—')}</td><td>${escapeHtml(r.specialty)}</td><td><a href="mailto:${encodeURIComponent(r.email)}">${escapeHtml(r.email || '—')}</a><small>${escapeHtml(r.phone || '')}</small></td><td>${r.duplicate ? `<span class="duplicate-badge">Duplicado · ${escapeHtml(r.duplicateSpecialties.join(', '))}</span>` : '<span class="ok-badge">Registro único</span>'}</td><td><button class="table-action" data-record="${r.index}" type="button">Agendar</button></td></tr>`).join('') : '<tr><td colspan="6">No hay registros para este filtro.</td></tr>'; $$('.table-action', db).forEach(btn => btn.addEventListener('click', () => { const r = csvState.records.find(x => x.index === Number(btn.dataset.record)); if (!r) return; $('#teacher-candidate').value = r.name; $('#teacher-candidate-email').value = r.email; $('#teacher-candidate-contact').value = r.phone; $('#teacher-specialty').value = r.specialty; teacherAgenda.scrollIntoView({ behavior: 'smooth', block: 'center' }); })); }
  $('#csv-upload').addEventListener('change', async e => { const file = e.target.files[0]; if (!file) return; csvState.records.splice(0, csvState.records.length, ...prepareRecords(csvParse(await file.text()))); csvState.filter = $('.specialty-tab.active')?.dataset.specialty || 'Todas'; renderDatabase(); e.target.value = ''; });
  $$('.specialty-tab').forEach(tab => tab.addEventListener('click', () => { csvState.filter = tab.dataset.specialty; renderDatabase(); }));
  renderDatabase();
  $('#save-appointment').addEventListener('click', e => { e.stopImmediatePropagation(); const date = $('#teacher-appointment-date').value, name = $('#teacher-candidate').value.trim(), email = $('#teacher-candidate-email').value.trim(), professor = $('#teacher-professor').value.trim(), sender = $('#teacher-sender-email').value.trim(), specialty = $('#teacher-specialty').value, type = $('#teacher-appointment-type').value, time = $('#teacher-appointment-time').value, message = $('#teacher-appointment-message'); if (!date || !name || !email || !professor || !sender) { message.textContent = 'Completá estudiante, correo del estudiante, profesor, fecha y correo del docente.'; message.classList.add('error'); sendButton.disabled = true; return; } const subject = encodeURIComponent(`Confirmación de cita STN · ${date} · ${time}`), body = encodeURIComponent(`Hola ${name},\n\nConfirmamos tu cita de ${type.toLowerCase()} en la Sección Técnica Nocturna.\n\nFecha: ${date}\nHora: ${time}\nEspecialidad: ${specialty}\nProfesor a cargo: ${professor}\nCorreo del docente: ${sender}\n\nPara consultas: 6195-5775.`); pendingMailto = `mailto:${encodeURIComponent(email)}?subject=${subject}&body=${body}`; sendButton.disabled = false; message.classList.remove('error'); message.textContent = '✓ Cita preparada. Presioná “Enviar confirmación” para abrir el correo del docente.'; const appointments = getAppointments(); appointments.push({ specialty, type, date, time, name, email, professor, sender }); localStorage.setItem('stn-appointments', JSON.stringify(appointments)); updateDashboard(); }, true);
  sendButton.addEventListener('click', () => { if (pendingMailto) window.location.href = pendingMailto; });
}
